name: web3dart_builders
description: Extension of the web3dart package that includes the dart contract generator from abi.
version: 0.0.7
repository: https://github.com/tct68/web3dart_builders
homepage: https://github.com/tct68/web3dart_builders
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.3.1
  code_builder: ^4.5.0
  built_collection: ^5.1.1
  path: ^1.8.3
  dart_style: ^2.2.4
  web3dart:
    git:
      url: https://github.com/tct68/web3dart.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  build_config: ^1.1.1
  build_test: ^2.1.6
